### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Azimer**

### CODE REVIEW

**Comment by cxd4** [comment]
Cool!  Most people stay away from GPLv3, but I don't really know anything about the differences so just use that because GNU says do it.

The only thing that bothers me about licensing is sticking the extra KB of text at the header of every source file.  I've never done that, just put the LICENSE/COPYING/whatever file in the repository by itself to explain the license.  Not sure if adding the commented headers re-indicating the license was also legally necessitated in some measure.

**Comment by Azimer** [comment]
I don't know other than it makes it explicit.  Do you think it matters?  GPL basically means everything needs to stay open source and you can't change the license ever.  I don't care.  What I want to avoid is someone taking the code, changing the branding and trying to sell it on google play.  If you have a better idea, please submit to this branch and I will review.  If I like, I will take your changes.

**Comment by cxd4** [comment]
Oh, I'm not picky about licenses at all.  I do understand that GPLv3 is the most protective against issues like that, though.  I was only complaining about me never putting the license bits in the headers of the source files themselves because it adds stuff insignificant to the code and maintaining and reading it.

**Comment by Azimer** [comment]
Should we abbreviate?

```C
/*
    Apollo64 - Cross-platform Nintendo 64 emulator
    Copyright (C) 2017 - Azimer - http://www.apollo64.com/
	
	This program is distributed under the GNU General Public License v3.
	See the LICENSE document supplied with this source code for details.
*/
```

**Comment by cxd4** [comment]
That looks a bit easier on the eyes.  In fact that's what ecsv from Mupen64Plus did when he PR'd a licensing change to my RSP project.  He put like the last sentence of the CC0 legal terms in all the files and referred to the license text file externally kind of like you just wrote.

**Pull request merged**
